---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
##一次性展示多个interactivity plots

##一开始不把dashboard放到repo里面是因为想要以dashboard的形式展示数据看一看，一旦放入repo中，这个文件就会以website page的形式展现而不是dashboard

##在console中运行这段code就可以生成一个html文件，点开就是dashboard的形式--[`rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")`]


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |> 
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating,
    price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price) 
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

### Chart C

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~n,
    type = "bar"
  )
```

