---
title: "Here are some plotly plots"
output: html_document
---
Interactivity is great.

plotly和dashboard都是属于有interactivity的


here 's the tidyverse
##因为这是一个给别人看的website，去掉不必要的信息

```{r, message=FALSE}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```


Let's load the AirBnB dataset

##为了防止每次在网站上打开这个plot的时候都需要加在一个huge huge dataset，我们只`select`我们需要的数据

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |> 
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating,
    price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```



Let's make a scatterplot!!!!but interactive this time

##`str_c()`--combine string variable together--Price: $+对应价格

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price) 
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

若想要一次展示多个text形式的信息

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "Rating: ", rating) 
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

若想要换行排列--`\n`--a new line

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "\nRating: ", rating) 
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```


